networks:
  lan:
      external: true

services:

  mysearch-proxy:
    image: skernelx/mysearch-proxy:latest
    container_name: mysearch-proxy
    ports:
      - "9874:9874"
    networks:
      - lan
    environment:
      - ADMIN_PASSWORD=${ADMIN_PW}
    volumes:
      - ${DATA}/mysearch/proxy:/app/data
    restart: unless-stopped

  mysearch-mcp:
    image: mysearch-mcp:latest
    container_name: mysearch-mcp
    ports:
      - "8000:8000"
    networks:
      - lan
    environment:
      - MYSEARCH_PROXY_BASE_URL=${MYSEARCH_URL}
      - MYSEARCH_PROXY_API_KEY=${MYSEARCH_API}
    restart: unless-stopped
