networks:
  lan:
      external: true

services:

  ds2api:
    image: ghcr.io/cjackhwang/ds2api:latest
    container_name: ds2api
    restart: always
    networks:
      - lan
    ports:
      - "5001:5001"
    volumes:
      - ${DATA}/ds2api/config.json:/app/config.json    # 配置文件
      # - ./.env:/app/.env                  # 环境变量
    environment:
      - TZ=Asia/Shanghai
      - LOG_LEVEL=INFO
      - DS2API_ADMIN_KEY=${DS2API_ADMIN_KEY:-ds2api}

  aistudio2api:
    # image: hkfires/aistudiobuildws:latest
    build: https://github.com/hkfires/AIStudioBuildWS.git
    container_name: aistudio2api
    environment:
      - CAMOUFOX_INSTANCE_URL=${AIBUILD_URL}
      - CAMOUFOX_PROXY=${AIBUILD_PROXY}
    volumes:
      - ${DATA}/buildws/cookies:/app/cookies:rw
      - ${DATA}/buildws/logs:/app/logs:rw
    restart: always
    networks:
      - lan
    deploy:
      resources:
        limits:
          cpus: '2'       # 限制最多使用 2 个 CPU 核心
          memory: 4G        # 限制内存最大为 2GB
        reservations:
          memory: 2G      # 保证至少分配 512M 内存

  cli-proxy-api:
    image: eceasy/cli-proxy-api:latest
    container_name: cli-proxy-api
    networks:
      - lan
    ports:
      - "8317:8317"
      # - "8085:8085"
      # - "1455:1455"
      # - "54545:54545"
      # - "11451:11451"
      # - "51121:51121"
    volumes:
      - ${DATA}/CLIProxyAPI/config.yaml:/CLIProxyAPI/config.yaml
      - ${DATA}/CLIProxyAPI/auths:/root/.cli-proxy-api
      - ${DATA}/CLIProxyAPI/logs:/CLIProxyAPI/logs
    restart: unless-stopped

  # gemini-fastapi:
  #   image: ghcr.io/luuquangvu/gemini-fastapi:latest
  #   container_name: gemini-fastapi
  #   # ports:
  #   #   - "18001:8000"
  #   networks:
  #     - lan
  #   volumes:
  #     - ${DATA}/gemini-fastapi/config:/app/config  # Uncomment to use a custom config file
  #     # - ${DATA}/certs:/app/certs        # Uncomment to enable HTTPS with your certs
  #     - ${DATA}/gemini-fastapi/data:/app/data
  #     - ${DATA}/gemini-fastapi/cache:/app/cache
  #   environment:
  #     - GEMINI_COOKIE_PATH=/app/cache
  #   restart: always

  grok2api:
    # image: 'tomiya233/grok2api:latest'
    # build: https://github.com/Tomiya233/grok2api.git
    image: ghcr.io/chenyme/grok2api:latest
    container_name: grok2api
    # ports:
    #   - "18000:8000"
    volumes:
      - ${DATA}/grok2api:/app/data
      - ${DATA}/grok2api/logs:/app/logs
    environment:
      # - STORAGE_MODE=file
      TZ: Asia/Shanghai
      LOG_LEVEL: INFO
      SERVER_PORT: 8000
      SERVER_WORKERS: 1
      SERVER_STORAGE_TYPE: local
    networks:
      - lan
    restart: always

  claude2api:
    image: pushzx/claude2api:latest-arm64
    container_name: claude2api
    restart: unless-stopped
    networks:
      - lan
    # ports:
    #   - "${PORT:-8080}:8080"
    environment:
      - LISTEN_ADDR=:8080
      - CLAUDE_SESSION_KEYS=${CLAUDE_SESSION_KEYS}
      - ADMIN_USER=${CLAUDE_ADMIN_USER}
      - ADMIN_PASS=${CLAUDE_ADMIN_PASS}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - PROXY_HOST=http://gluetun
      - PROXY_PORT=8888

  # gemini-business2api:
  #   image: cooooookk/gemini-business2api:latest
  #   container_name: gemini-business2api
  #   # ports:
  #   #   - "7860:7860"
  #   volumes:
  #     - ${DATA}/business2api:/app/data
  #   networks:
  #     - lan
  #   environment:
  #     - ADMIN_KEY=${DS2API_ADMIN_KEY}
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s

  # gcli2api:
  #   image: ghcr.io/su-kaka/gcli2api:latest
  #   container_name: gcli2api
  #   restart: unless-stopped
  #   ports:
  #     - "7861:7861"
  #   networks:
  #     - lan
  #   environment:
  #     - PORT=7861
  #     # 或使用分离密码（推荐用于生产环境）
  #     - API_PASSWORD=${GCLI2API_API}
  #     - PANEL_PASSWORD=${GCLI2API_PASSWORD}
  #   volumes:
  #     - ${DATA}/gcli2api/creds:/app/creds
  #   # healthcheck:
  #   #   test: ["CMD-SHELL", "python -c \"import sys, urllib.request, os; port = os.environ.get('PORT', '7861'); req = urllib.request.Request(f'http://localhost:{port}/v1/models', headers={'Authorization': 'Bearer ' + os.environ.get('PASSWORD', 'pwd')}); sys.exit(0 if urllib.request.urlopen(req, timeout=5).getcode() == 200 else 1)\""]
  #   #   interval: 30s
  #   #   timeout: 10s
  #   #   retries: 3
  #   #   start_period: 40s

  # clewdr:
  #   image: ghcr.io/xerxes-2/clewdr:latest
  #   container_name: clewdr
  #   volumes:
  #     - ${DATA}/clewdr:/etc/clewdr
  #   networks:
  #     - lan
  #   # ports:
  #   #   - "8484:8484"
  #   restart: unless-stopped
