networks:
  lan:
      external: true

services:

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - lan
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - ${DATA}/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=purevpn
      # - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=${OVPN_USER}
      - OPENVPN_PASSWORD=${OVPN_PW}
      - SERVER_CITIES=${OVPN_SVRS}
      # Timezone for accurate log times
      - TZ=Asia/Shanghai
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=72h
      - HTTPPROXY=on

  # subconverter:
  #   image: 'asdlokj1qpi23/subconverter:latest'
  #   container_name: subconverter
  #   networks:
  #     - lan
  #   ports:
  #     - "25500:25500"
  #   restart: unless-stopped

  it-tools:
    image: 'corentinth/it-tools:latest'
    container_name: it-tools
    networks:
      - lan
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # wsocks:
  #   image: ghcr.io/ccbkkb/microwarp:latest
  #   container_name: wsocks
  #   privileged: true
  #   restart: always
  #   networks:
  #     - lan
  #   ports:
  #     - "19091:9091"
  #   environment:
  #     - BIND_ADDR=0.0.0.0     # 监听地址 (默认 0.0.0.0)
  #     - BIND_PORT=9091        # 监听端口 (默认 1080)
  #     # - SOCKS_USER=admin      # SOCKS5 认证用户名 (留空则为无密码模式)
  #     # - SOCKS_PASS=123456     # SOCKS5 认证密码
  #     # - GH_PROXY=https://github.ednovas.xyz # 代理 wgcf 二进制下载地址
  #     - ENDPOINT_IP=162.159.192.1:4500
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   volumes:
  #     - ${DATA}/microwarp:/etc/wireguard # Keep account data to avoid rate limits


  vaultwarden:
    image: 'vaultwarden/server:latest'
    container_name: vaultwarden
    environment:
      - 'DOMAIN=${VW_DOMAIN}'
      - 'SIGNUPS_ALLOWED=false'
    networks:
      - lan
    volumes:
      - '${DATA}/vw:/data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 2s
      timeout: 10s
      retries: 15
    restart: unless-stopped

  syncthing:
    image: 'lscr.io/linuxserver/syncthing:latest'
    container_name: syncthing
    environment:
      - 'TZ=Asia/Shanghai'
      - 'PUID=0'
      - 'PGID=0'
    volumes:
      - '${DATA}/syncthing/config:/config'
      - '${DATA}/syncthing/data1:/data1'
    networks:
      - lan
    ports:
      # - '8384:8384'
      - '22000:22000/tcp'
      - '22000:22000/udp'
      - '21027:21027/udp'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8384/rest/noauth/health"]
      interval: 5s
      timeout: 20s
      retries: 10
    restart: unless-stopped
